name = "Quads"
uuid = "08656640-f1d2-11e9-0117-d3d99a376d3a"
authors = ["Adam Massachi"]
version = "0.1.0"

[compat]
julia = "1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
